### ISSUE TITLE
Unable to copy annotation title

### ISSUE THREAD

**Issue by ei8fdb** [madebyfabian/figma-plugin-annotate-it#2] opened 2021-04-26 15:19 UTC
Hi, I'm using your plugin to annotate designs. I need to copy and paste annotation title and body into email/git issue. 

Expected behaviour:
1. highlight annotation title
2. copy text (ctrl-c or right click and copy)
3. switch to other window
4. paste text (ctrl-v or right click and paste)

Actual behaviour:
cannot copy and paste text

It's only possible to copy and paste the annotation body, not the title. See video screenshot:

https://user-images.githubusercontent.com/1899506/116107412-eca7c080-a6aa-11eb-962d-b44a60516c25.mov

**Comment by madebyfabian** [comment] 2021-04-26 16:04
Hey there,
thanks for using Annotate it!
I will look into this and will try to reproduce it, since this really looks like an unwanted behavior to me, you should absolutely be able to copy/paste the contents of the title.

**Comment by ei8fdb** [comment] 2021-04-26 16:34
> Hey there,
> thanks for using Annotate it!
> I will look into this and will try to reproduce it, since this really looks like an unwanted behavior to me, you should absolutely be able to copy/paste the contents of the title.

Thanks for making Annotate It! @madebyfabian, and for replying. The bug did seem odd. I'll wait to hear from you.

**Comment by madebyfabian** [comment] 2021-04-30 16:23
Hey there,
I've tried to recreate it, for me, the copy/pasting/selecing behaviour works perfectly.
I use an M1 iMac with MacOS 11.1, and I use the Native Figma App in the latest Version (v97.7). I also tried opening Figma in the Chrome Browser, same result. Works for me. For comparison, which setup do you use?

**Comment by madebyfabian** [comment] 2021-05-21 09:15
Can I close the issue? Or are these problems still existant for you @ei8fdb ?

**Closed** 2021-08-20 13:57 UTC
